# Jekyll 配置（重构后精简版）
name: Hyper-Space
description: Unlinear Space
url: "https://hypergroups.top"
baseurl: ""

github: HyperGroups

permalink: /:title

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

collections:
  post_renovated:
    output: true
    permalink: /:title

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - dev
  - .gitignore
  - Pages
